name: example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rocm-5.5.0-ubuntu-jammy
      
    steps:
    - name: rocm-setup
      uses: neoblizz/rocm-setup@main
      with:
        rocm: '5.5.0'
        
    - name: check-rocm-docker
      run: |
          docker image ls
          docker run --name ${{ env.IMAGE_NAME }} sh -c "hipcc --version"
