name: example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: rocm-setup
      uses: neoblizz/rocm-setup@v0.1.1-beta
      with:
        rocm: '5.5.0'
