name: example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: rocm-setup
      uses: neoblizz/rocm-setup@main
      with:
        rocm: '5.5.0'
        
    - name: check-rocm-docker
      run: docker container ls
