name: example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: rocm-setup
      uses: neoblizz/rocm-setup@v0.1.3-beta
      with:
        rocm: '5.5.0'
    - name: Check if running inside Docker
      run: |
          if grep -q "/docker/" /proc/1/cgroup; then
            echo "Running inside Docker"
          else
            echo "Not running inside Docker"
          fi
    - name: Check if Docker is installed
      run: |
          if command -v docker &> /dev/null; then
            echo "Docker is installed"
            docker images
          else
            echo "Docker is not installed"
          fi
