name: ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rocm-5.5.0-ubuntu-jammy
      DOCKER_DEVICES: ""
      # maawad: Eventually we need to uncomment this out
      # See: https://github.com/neoblizz/rocm-setup/issues/5
      #DOCKER_DEVICES: "--device=/dev/kfd --device=/dev/dri"
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}
    
    # we don't need to run anything anymore
    #- name: Run the docker container
    #  run: docker run -t --name rocm-container ${{ env.DOCKER_DEVICES }} ${{ env.IMAGE_TAG }}
   
    - name: Check if running inside Docker
      run: |
          if grep -q "/docker/" /proc/1/cgroup; then
            echo "Running inside Docker"
          else
            echo "Not running inside Docker"
          fi
    - name: Check if Docker is installed
      run: |
          if command -v docker &> /dev/null; then
            echo "Docker is installed"
            docker images
          else
            echo "Docker is not installed"
          fi
