name: ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: my-image-name:${{ github.run_number }}
      DOCKER_DEVICES: ""
      # maawad: Eventually we need to uncomment this out
      # See: https://github.com/neoblizz/rocm-setup/issues/5
      #DOCKER_DEVICES: "--device=/dev/kfd --device=/dev/dri"
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}
    - name: Run the docker container
      run: docker run -it --name rocm-container ${{ env.DOCKER_DEVICES }} ${{ env.IMAGE_NAME }}
